name: Update GB Prices

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - run: xvfb-run -a python update_gsheet_prices.py
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
